export default{
    formatDate(date) {  
        let y = date.getFullYear();  
        let m = date.getMonth() + 1;  
        let d = date.getDate();     
        return y + '-' + m + '-' + d;  
    },
    // GetDateStr(AddDayCount){
    //     var dd = new Date();
    //     dd.setDate(dd.getDate() + AddDayCount);//获取AddDayCount天后的日期
    //     var y = dd.getFullYear();
    //     var m = (dd.getMonth() + 1) < 10 ? "0" + (dd.getMonth() + 1) : (dd.getMonth() + 1);//获取当前月份的日期，不足10补0
    //     var d = dd.getDate() < 10 ? "0" + dd.getDate() : dd.getDate();//获取当前几号，不足10补0
    //     return y + "-" + m + "-" + d;
    // },
    getDayDetail(){
        let dayDetailArr = [{
            punchAddress: "北京市朝阳区太阳宫中路16号院1号楼冠捷大厦",
            punchBeginTime: "08:57",
            punchendTime: "18:03",
            staffName: "郭丽",
            status: "正常"
        },{
            punchAddress: "北京市朝阳区太阳宫中路16号院1号楼冠捷大厦",
            punchBeginTime: "09:06",
            punchendTime: "18:06",
            staffName: "李抆霞",
            status: "异常"
        },{
            punchAddress: "北京市朝阳区太阳宫中路16号院1号楼冠捷大厦",
            punchBeginTime: "08:23",
            punchendTime: "17:39",
            staffName: "张玉龙",
            status: "正常"
        }]
        return dayDetailArr
    },
    getLeaveType(){
        let data = {
            loaType:{
                0: "请假",
                1: "加班",
                2: "考勤",
                3: "报派工",
                4: "批量加班"
            },
            myattence: {
                0: 0,
                1: 1,
                2: 3,
                3: 4,
                4: 5,
                5: 6,
                6: 7,
                7: 8,
                8: 9,
                9: 13,
                10: 14,
                11: 15,
                12: 16
            },
            myabsence:{
                0:0,
                1:2,
                2:3,
                3:4,
                4:5,
                5:6,
                6:7,
                7:8,
                8:9,
                9:13,
                10:14
            },
            leaveType:{
                0: "请选择",
                1: "因公",
                2: "调休",
                3: "病假",
                4: "事假",
                5: "年假",
                6: "婚假",
                7: "产假",
                8: "哺乳假",
                9: "丧假",
                10: "迟到",
                11: "早退",
                12: "旷工",
                13: "产检假",
                14: "陪产假",
                15:"分包替岗",
                16:"漏打卡"
            },  
            relaxation:{
                0:"调休",
                1:"有偿"
            },
            processStatus:{
                0 : "未提交",
                1 : "审批中",
                2 : "已审批",
                3: "修改"
            },
        }
        return data;
    },

    getDataTable(wholeMonth,month){
        let tableData = [];
        console.log(month == "2019-9");
        if(month == "2019-9"){     
            if(wholeMonth=='1'){
                tableData = [
                    {
                        id:661390,
                        addrId:10895,
                        punchDate:'2019-9-2',
                        beginTime:'9:30',
                        endTime:'17:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:'',
                        addrId:10867,
                        punchDate:'2019-9-5',
                        beginTime:'09:10',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },{
                        id:677341,
                        addrId:10947,
                        punchDate:'2019-9-6',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        isNew:1,
                        leaveType:1,
                        processStatus:2,
                        groupId:10154,
                        prjId:10154,
                    },{
                        id:681679,
                        addrId:662,
                        punchDate:'2019-9-9',
                        beginTime:'9:30',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        isNew:1,
                        leaveType:1,
                        processStatus:1,
                        groupId:10154,
                        prjId:10154,
                    },
                ]
            }else{
                tableData = [
                    {
                        id:661390,
                        addrId:10895,
                        punchDate:'2019-9-2',
                        beginTime:'9:30',
                        endTime:'17:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:'',
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:664515,
                        addrId:10947,
                        punchDate:'2019-9-3',
                        beginTime:'9:00',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:'',
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:668512,
                        addrId:10867,
                        punchDate:'2019-9-4',
                        beginTime:'9:00',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:'',
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:672486,
                        addrId:10867,
                        punchDate:'2019-9-5',
                        beginTime:'09:10',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:677341,
                        addrId:10947,
                        punchDate:'2019-9-6',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        leaveType:1,
                        isNew:1,
                        processStatus:2,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:681679,
                        addrId:662,
                        punchDate:'2019-9-9',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        leaveType:1,
                        isNew:1,
                        processStatus:1,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:'',
                        addrId:662,
                        punchDate:'2019-9-17',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'',
                        leaveType:0,
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:'',
                        addrId:662,
                        punchDate:'2019-9-18',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'',
                        leaveType:0,
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },   
                    {
                        id:'',
                        punchDate:'2019-9-29',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        isNew:0,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },            
                ]
            }
        }else{
            if(wholeMonth=='1'){
                tableData = [
                    {
                        id:672486,
                        addrId:10867,
                        punchDate:'2019-8-6',
                        beginTime:'09:10',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:677341,
                        addrId:10947,
                        punchDate:'2019-8-7',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        leaveType:1,
                        isNew:1,
                        processStatus:2,
                        groupId:10154,
                        prjId:10154,
                    },
                ]
            }else{
                tableData = [
                    {
                        id:661390,
                        addrId:10895,
                        punchDate:'2019-8-1',
                        beginTime:'9:00',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:'',
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:664515,
                        addrId:10947,
                        punchDate:'2019-8-2',
                        beginTime:'9:00',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:'',
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:668512,
                        addrId:10867,
                        punchDate:'2019-8-5',
                        beginTime:'9:00',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:'',
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:672486,
                        addrId:10867,
                        punchDate:'2019-8-6',
                        beginTime:'09:10',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        reason:'',
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:677341,
                        addrId:10947,
                        punchDate:'2019-8-7',
                        beginTime:'',
                        endTime:'',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        leaveType:1,
                        isNew:1,
                        processStatus:2,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:681679,
                        addrId:662,
                        punchDate:'2019-8-8',
                        beginTime:'09:00',
                        endTime:'18:00',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'因公',
                        leaveType:1,
                        isNew:1,
                        processStatus:1,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:'',
                        addrId:662,
                        punchDate:'2019-8-9',
                        beginTime:'09:00',
                        endTime:'18:20',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'',
                        leaveType:0,
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },
                    {
                        id:'',
                        addrId:662,
                        punchDate:'2019-8-12',
                        beginTime:'08:20',
                        endTime:'17:30',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        reason:'',
                        leaveType:0,
                        isNew:1,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },   
                    {
                        id:'',
                        punchDate:'2019-8-30',
                        beginTime:'08:59',
                        endTime:'18:05',
                        absBeginTime:'09:00',
                        absEndTime:'18:00',
                        leaveType:0,
                        isNew:0,
                        processStatus:0,
                        groupId:10154,
                        prjId:10154,
                    },            
                ]
            }
        }
        return tableData;
    }
}